name: Sync packages

on:
  push:
    paths:
      - '.github/workflows/small7.yml'
      - 'diy/**'
  schedule:
    - cron: 0 */12 * * *
  watch:
    types: started
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    name: Update ${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        target: [main]
        
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        ref: 'main'

    - name: Initialization environment
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Shanghai"
        
    - name: Clone packages
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x ${{matrix.target}}.sh
        git clone -b ${{matrix.target}} https://github.com/kenzok78/small-package.git ${{matrix.target}}
        cd ${{matrix.target}}
        git rm -r --cache * >/dev/null 2>&1 &
        rm -rf `find ./* -maxdepth 0 -type d ! -name "diy"` >/dev/null 2>&1
        $GITHUB_WORKSPACE/${{matrix.target}}.sh
        
    # Building a multiline commit message
    - run: echo "Commit $PKG_VERSION 1" >> commitmessage.txt
    - run: echo "Commit $PKG_VERSION 2" >> commitmessage.txt
    - run: echo "Commit $PKG_VERSION 3" >> commitmessage.txt
    - run: echo "Commit $PKG_VERSION 4" >> commitmessage.txt
    - run: echo "Commit $PKG_VERSION 5" >> commitmessage.txt
    - run: echo "Commit $PKG_VERSION 6" >> commitmessage.txt
    - run: echo "Commit $PKG_VERSION 7" >> commitmessage.txt
    - run: echo "Commit $PKG_VERSION 8" >> commitmessage.txt
    - run: echo "Commit $PKG_VERSION 9" >> commitmessage.txt
    - run: echo "Commit $PKG_VERSION 10" >> commitmessage.txt


    # Create a multiline string to be used by the git-auto-commit Action
    - name: Set commit message
      id: commit_message_step
      run: |
        echo 'commit_message<<EOF' >> $GITHUB_OUTPUT
        cat commitmessage.txt >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    # Quick and dirty step to get rid of the temporary file holding the commit message
    - run: rm -rf commitmessage.txt

    - uses: stefanzweifel/git-auto-commit-action@v4
      id: commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        commit_message: ${{ steps.commit_message_step.outputs.commit_message }}	

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
